# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "go-ci" ]
  pull_request:
    branches: [ "go-ci" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      
    - name: Build DB
      run: cd api_rest_gin_go-ci && docker-compose build

    - name: Create DB
      run: cd api_rest_gin_go-ci && docker-compose up -d

    - name: Test
      run: cd api_rest_gin_go-ci && go test -v main_test.go
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build 
      run: cd api_rest_gin_go-ci && go build -v main.go
